### ISSUE TITLE
Sidebar display problems.

### ISSUE THREAD

**Issue by Johncdy** [adam-stokes/hexo-theme-striped#1]
This theme is very nice,but it still has a problem that if slidebar has too many contents,the background img won't repeat.

**Comment by adam-stokes** [comment]
Thanks for the heads up I'll see about fixing that

**Comment by Johncdy** [comment]
![56ff0019-8b90-4842-8e59-a9c9e4cbce07](https://f.cloud.github.com/assets/1948685/1655266/32f6b4aa-5b5f-11e3-858b-6054a251f282.png)
Maybe this could help you.

**Comment by adam-stokes** [comment]
perfect thanks!

**Comment by Johncdy** [comment]
I'm sorry this problem still exist, you can visit this website page(http://johncdy.me/archives/).

**Comment by Johncdy** [comment]
Yes,this time it works nice!

**Comment by adam-stokes** [comment]
Awesome, thanks for testing!
