### ISSUE TITLE
head is <h2>, and ## in post's markdown is <h2> as well

### ISSUE THREAD

**Issue by zizhengwu** [adam-stokes/hexo-theme-striped#3]
it's quite confusing

**Comment by adam-stokes** [comment]
@Dustland could you provide me with some code snippet where you see this? 

Thanks!

**Comment by zizhengwu** [comment]
Hi @battlemidget , happy to see your reply. But I'm sorry that I'm not familiar with CSS or hexo theme.

However, it seems that, apart form heading is <h2> and ## in post's markdown is <h2>, <h3> and <h4> are of the same size?

Best wishes

**Comment by adam-stokes** [comment]
@Dustland , I'll go back and double check the font sizes between the headings in the html and those generated from the markdown parser
