### ISSUE TITLE
Default homepage being generated

### ISSUE THREAD

**Issue by cmsimike** [adam-stokes/hexo-theme-striped#4]
hexo: 2.4.4
Whenever I generate my static blog site, the index.html at the root of the blog is the page located here: http://html5up.net/striped/

Is this expected? Or am I missing something daft.

**Comment by adam-stokes** [comment]
Interesting, is your blog source public somewhere I could clone it and reproduce?

**Comment by geekplux** [comment]
r u set the 「url」in _config.yml which in you hexo-blog root dictionary?  I used this theme, no problem

**Comment by cmsimike** [comment]
@battlemidget No but I can archive and somehow deliver to you if you'd like?
@geekplux yup it is set.

**Comment by adam-stokes** [comment]
@cmsimike , sure if you have dropbox.com or something you can share it with my email: adam.stokes@gmail.com

**Comment by cmsimike** [comment]
@battlemidget I was wondering if you got my email with the attachment?

**Comment by adam-stokes** [comment]
@cmsimike I just checked and downloading now, ill have a look at it in a couple of hours

Thanks!

**Comment by cmsimike** [comment]
Thanks! Didn't meant to rush you. Just wanted to make sure you got the email.

**Comment by ShukriChiu** [comment]
ok, I meet the same problem. It's that the author put index.html in theme/source folder.  you can remove it .. but another problem is that if remove the index.html, your site will not display correctly in mobile ..

**Comment by adam-stokes** [comment]
ok im still looking into this, thanks for the feedback

**Comment by adam-stokes** [comment]
sorry this was fixed in upstream already
