### ISSUE TITLE
Why always localhost:4000/#

### ISSUE THREAD

**Issue by jenenliu** [adam-stokes/hexo-theme-striped#5]
I modify the _config.yml in striped directory, here is the menu part I modify, and just this part

menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about

After I run 'hexo g' and 'hexo s',  I go to  localhost:4000, but whatever I click, such as
'about', 'Archives', nothing changed, and the url is always the same 'localhost:4000/#'

Sorry for my English, and your theme is awesome, how can I make it works, thanks ;)

**Comment by adam-stokes** [comment]
Ill take a look and see whats going on, thanks!

**Comment by uwenda** [comment]
same with me.

**Comment by Burhh** [comment]
hello ,how can i modify the favicon . there is no link-rel"icon" tag in the head.ejs.

**Comment by ZwEin27** [comment]
I encounter the same question, and I fix it by deleting the file named `index.html` in `striped` dictionary.

**Comment by adam-stokes** [comment]
Should be fixed in latest upstream
